{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  namespace: {{ .Values.app.name }}-{{ .Values.environment }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        # Phrase endpoint - main requirement
        location /phrase {
            access_log off;
            return 200 "Hello from NGINX {{ .Values.environment | upper }}!\n";
            add_header Content-Type text/plain;
        }

        # Environment info endpoint
        location /env {
            access_log off;
            return 200 "Environment: {{ .Values.environment | upper }}\nVersion: {{ .Values.app.version }}\n";
            add_header Content-Type text/plain;
        }

        # Static files
        location / {
            try_files $uri $uri/ /index.html;
            expires 1d;
            add_header Cache-Control "public, immutable";
        }

        # Error pages
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }
{{- end }}
